#!/usr/bin/env bash
set -euo pipefail

# Scripts
# Initialises the project
initialise() {
	# Check for arguments
	[ $# -ge 1 ] && dir_name="$1" || dir_name="."
	local proj_name=${dir_name}

	if [[ "${proj_name}" == "." ]]; then
		proj_name=$(basename ${PWD})
	fi

	template="${HOME}/.config/cpp_template/init"

	! [ -e ${template} ] && fail "Template not found at ${template}"

	# Copy files from template
	rsync -av --exclude='.git' --exclude='build/' "${template}"/ ${dir_name}/
	cd ${dir_name}

	# Configure project name
	sed -i \
		's/^set([[:space:]]*MAIN_TARGET[[:space:]]*".*")/set(MAIN_TARGET "'"${proj_name}"'")/' CMakeLists.txt

	# Initialise git repo
	git init
}

# Adds a library to the project in the current folder
add_lib() {
	# Check for argument count
	[ $# -lt 1 ] && fail "Usage::$0 lib <library_name>"

	# Check if a file by the name already exists
	local dir_name="$1"
	[ -e ${dir_name} ] && fail "${dir_name} already exists"

	# Create library structure
	lower_case=$(basename ${dir_name})
	file_name="${lower_case^}"
	mkdir ${dir_name}
	cd ${dir_name}
	mkdir include/ src/ tests/
	touch src/${file_name}.cpp include/${file_name}.hpp
	
	# Generate CML
	cat <<- EOF > CMakeLists.txt
	cmake_minimum_required(VERSION 4.0)
	project(${file_name} LANGUAGES CXX)

	# Configure library and dependencies
	add_library(${lower_case} OBJECT)
	target_sources(${lower_case}
		PRIVATE
		src/${file_name}.cpp

		PUBLIC
		FILE_SET HEADERS
		BASE_DIRS include/
		FILES
		include/${file_name}.hpp
	)

	# Enable Testing
	if(BUILD_TESTS)
		enable_testing()
		add_subdirectory(tests)
	endif()
	EOF

	# Add tests to the library
	add_test ${file_name}

	# Update parent CML with library linking
	cd ../
	echo -e "\n# Link library ${lower_case}" >> CMakeLists.txt
	echo -e \
	"add_subdirectory(${lower_case})\ntarget_link_libraries(\${MAIN_TARGET} ${lower_case})" >> CMakeLists.txt
}

add_test() {
	local proj_name="$1"
	local file_name=test${proj_name}

	cd tests/
	# Create a sample test file
	cat <<-EOF > ${file_name}.cpp
	int main() {
		return 0;
	}
	EOF
	
	# Write CMakeLists.txt
	cat <<- EOF > CMakeLists.txt
	add_executable(${file_name})

	target_sources(${file_name}
	PRIVATE
		${file_name}.cpp
	)

	target_link_libraries(${file_name}
	PRIVATE
		${proj_name,,}
	)

	function(make_test op)
		add_test(
			NAME \${op}
			COMMAND ${file_name} \${op}
		)
	endfunction()
	EOF

	# Exit the directory
	cd ../
}

# Builds the project
build() {
    [ $# -ge 1 ] && preset_name="$1" || preset_name="debug"
	cmake --preset ${preset_name}
}

# Deletes library from the project
delete() {
	# Check for argument count
	[ $# -lt 1 ] && fail "Usage::$0 delete <library_name>"

	local lib_name="$1"
	rm -r ${lib_name}
	sed -i.bak "/add_subdirectory(${lib_name})/d; /target_link_libraries.*${lib_name}/d" CMakeLists.txt
}

# Produce error message
fail() {
	echo $1 >&2
	exit 1
}

# Run the project
run() {
    [ $# -ge 1 ] && preset_name="$1" || preset_name="debug"
	build "$@"
	cmake --build build
}

# Run tests
run_test() {
	local preset_name="debug"
	local test_regex=""

	OPTIND=1
	while getopts ":d:R:" opt; do
		case "$opt" in
			d)
				preset_name="$OPTARG"
				;;
			R)
				test_regex="$OPTARG"
				;;
			\?)
				fail "cppgo test: invalid option -$OPTARG"
				;;
			:)
				fail "cppgo test: -$OPTARG requires an argument"
				return 1
				;;
		esac
	done

	# Run tests
	build ${preset_name}
	if [[ -n "$test_regex" ]]; then
		ctest --test-dir build -R ${test_regex}
	else
		ctest --test-dir build
	fi
}


# Check if subcommand is passed
[ $# -lt 1 ] && \
fail "Use a subcommand: [build | delete | init | lib | run | test]"

# Dispatcher
script_name="$1"
shift 1

case "$script_name" in
    build)
		echo "Building project"
        build "$@"
        ;;
	delete)
		echo "Deleting library $1"
        delete "$@"
        ;;
	init)
		echo "Initialising project"
        initialise "$@"
        ;;
	lib)
		echo "Adding library $1"
        add_lib "$@"
        ;;
	run)
		echo "Running project"
        run "$@"
        ;;
	test)
		echo "Running tests $1"
        run_test "$@"
        ;;
    *)
		fail "Unrecognised subcommand: ${script_name}"
        ;;
esac
